name: Iris classification Deploy 

on: 
  push:
    branches: [main, master]
  workflow_dispatch:

jobs: 
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write #write isn't neccessary here, but good practise

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os}}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Smoke Test (import & help)
        run: |
          python -c "import server, torch; print('okay')"
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./Dockerfile
          push: false
          tags: iris-api:ci

  push-image-GHCR:
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write  #write is required to push to GHCR
    steps:
        - uses: actions/checkout@v4

        - name: Login to GHRC
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        
        - name: Build & push
          uses: docker/build-push-action@v6
          with:
              context: .
              file: ./Dockerfile
              push: true
              tags: |
                grhc.io/${{github.repository_owner}}/Iris_classification_Model-API:latest
                grc.io/${{github.repository_owner}}/iris-api:${{github.sha}}
